### ISSUE TITLE
Colour issue on string template variables in Javascript

### ISSUE THREAD

**Issue by prajapati-parth** [thenikso/github-plus-theme#15] opened 2020-03-12 05:08 UTC
When access an object's value using the dot notation, the dots are displayed on when the cursor is place on the dots, else it matches with the background colour.

Without cursor
![Screenshot 2020-03-12 at 10 34 18 AM](https://user-images.githubusercontent.com/17194534/76489112-749e1d00-644d-11ea-8ce4-23d4d0962660.png)

With cursor
![Screenshot 2020-03-12 at 10 34 39 AM](https://user-images.githubusercontent.com/17194534/76489129-7b2c9480-644d-11ea-8e04-2c3611a74a6f.png)

**Comment by zackkrida** [comment] 2020-03-20 19:03
Add this to your settings json file for vscode until the issue is fixed:

```json
 "editor.tokenColorCustomizations": {
    "[GitHub Sharp Dark]": {
      "textMateRules": [
        {
          "scope": [
            "keyword.operator.accessor",
            "meta.group.braces.round.function.arguments",
            "meta.template.expression",
            "markup.fenced_code meta.embedded.block"
          ],
          "settings": {
            "foreground": "#c3c6c9"
          }
        },
      ]
    },
```

**Comment by thenikso** [comment] 2021-08-26 10:22
thank you @zackkrida for the workaround. however this particular theme (GitHub Plus) only has a light background variant. so that has indeed been addressed in the other theme repo :)

**Closed as completed by thenikso** 2021-08-26 10:22 UTC
